sudo pacman -S --noconfirm --needed \
  alacritty \
  avahi \
  bash-completion \
  bat \
  blueberry \
  brightnessctl \
  btop \
  dust \
  eza \
  fastfetch \
  fcitx5 \
  fcitx5-gtk \
  fcitx5-qt \
  fd \
  ffmpegthumbnailer \
  fzf \
  gnome-keyring \
  gnome-themes-extra \
  gum \
  gvfs-mtp \
  hypridle \
  hyprland \
  hyprland-qtutils \
  hyprlock \
  hyprpicker \
  hyprshot \
  hyprsunset \
  imagemagick \
  impala \
  inetutils \
  jq \
  kvantum-qt5 \
  less \
  libqalculate \
  luarocks \
  mako \
  man \
  mariadb-libs \
  nautilus \
  noto-fonts \
  noto-fonts-cjk \
  noto-fonts-emoji \
  noto-fonts-extra \
  nss-mdns \
  nvim \
  pamixer \
  playerctl \
  plocate \
  plymouth \
  polkit-gnome \
  postgresql-libs \
  power-profiles-daemon \
  python-gobject \
  python-terminaltexteffects \
  ripgrep \
  satty \
  slurp \
  starship \
  swaybg \
  swayosd \
  tldr \
  tzupdate \
  ufw \
  ufw-docker \
  unzip \
  uwsm \
  walker-bin \
  waybar \
  wf-recorder \
  whois \
  wireplumber \
  wl-clip-persist \
  wl-clipboard \
  wl-screenrec \
  woff2-font-awesome \
  xdg-desktop-portal-gtk \
  xdg-desktop-portal-hyprland \
  xmlstarlet \
  yaru-icon-theme \
  yay \
  zoxide
